import { Box } from '@chakra-ui/react';
import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';

import { Provider } from '@/shared/ui/provider';
import ScrollToTopButton from '@/shared/ui/scroll-to-top-button';

// import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Provider>
          <Box as='main'>{children}</Box>
          <ScrollToTopButton />
          <Box as='footer' h='800px' bg='blue.300'>
            <p>Footer</p>
          </Box>
        </Provider>
      </body>
    </html>
  );
}
