import { Box } from '@chakra-ui/react';
import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import { notFound } from 'next/navigation';
import { NextIntlClientProvider } from 'next-intl';
import { getLocale, getMessages, setRequestLocale } from 'next-intl/server';
import type { PropsWithChildren } from 'react';

import {
  availableLocaleCodes,
  availableLocalesMap,
  defaultLocale,
  routing,
} from '@/shared/lib/i18n';
import type { Todo } from '@/shared/lib/utility-types';
import { Provider } from '@/shared/ui/provider';
import ScrollToTopButton from '@/shared/ui/scroll-to-top-button';

// import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export function generateStaticParams() {
  return routing.locales.map((locale) => ({ locale }));
}

async function LocaleLayout({ children }: PropsWithChildren) {
  const locale = await getLocale();

  // Ensure that the incoming `locale` is valid
  if (!routing.locales.includes(locale as Todo)) {
    notFound();
  }

  // Enable static rendering
  setRequestLocale(locale);

  if (!availableLocaleCodes.includes(locale)) {
    // throw new Error(`Unknown locale encountered: "${locale}".`);
    return null;
  }

  const { langDir, hrefLang } = availableLocalesMap[locale] || defaultLocale;

  // Providing all messages to the client
  // side is the easiest way to get started
  const messages = await getMessages();

  return (
    <html lang={hrefLang} dir={langDir} suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <NextIntlClientProvider messages={messages}>
          <Provider>
            <Box as='main'>{children}</Box>
            <ScrollToTopButton />
            <Box as='footer' h='800px' bg='blue.300'>
              <p>Footer</p>
            </Box>
          </Provider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}

export default LocaleLayout;
